const express = require('express')
const cors = require('cors')
const app = express()
const apiRouter = express.Router()
const internetAccountRouter = require('./routes/InternetAccountRouter')

app.use(require('./middlewares/responseMiddleware'))
app.use(express.json())
app.use(cors())
apiRouter.use('/internet-accounts', internetAccountRouter)
app.use('/api', apiRouter)
app.listen(3000)