const express = require('express')
const cors = require('cors')
const app = express()
const apiRouter = express.Router()
const internetAccountRouter = require('./routes/InternetAccountRouter')
const platformIconMapRouter = require('./routes/PlatformIconMapRouter')

app.use(require('./middlewares/responseMiddleware'))
app.use(express.json({limit: '5mb'}))
app.use(cors())
apiRouter.use('/internet-accounts', internetAccountRouter)
apiRouter.use('/platform-icon-maps', platformIconMapRouter)
app.use('/api', apiRouter)
app.listen(3000)